### ISSUE TITLE
Implement Skipper MVP

### ISSUE THREAD

**Issue by Jwpe** [cameronmaske/skipper#13]
@cameronmaske and I talked this through; lots of new ideas.
## Overview
- Skipper will be a host-agnostic deployment tool where the user defines services and groups.
- A **service** is represented by a single Docker container.
- Services are sorted into **groups** where a group is a series of services running on one or more **instances** (and load balancer).
- **Instances** are created automatically on the host, based on the groups defined by the user.
- Services are stored as **images** on the Docker registry. Skipper handles building and versioning from the user's codebase.
- Projects are configured using two files:
  - `skipper.yml`: project layout, groups and services 
  - '.skippercfg': host-specific credentials and weird settings (not version controlled)
### A small project running multiple containers on a single instance.

``` yml
name: demo
groups:
    demo:
        size: medium
        loadbalance:
            - "80:80"
        instances: 1
        services:
            web:
                build: .
                loadbalance:
                    - "80:8000"
                    - redis
            redis:
                image: redis
                loadbalance:
                    - "1234:1234"
```
### A production application pointing to services across multiple instances.

``` yml
name: demo
host: digital-ocean
groups:
    web:
        size: small
        loadbalance:
            - "80:80"
        instances: 1
        regions:
            - us-east-1
            - us-west-1
        links:
            - rabbitmq
            - db
            - redis
        services:
            web:
                build: .
                scale: 2
                loadbalance:
                    - "80:8000"
    tasks:
        size: large
        instances: 2
        links:
            - rabbitmq
            - db
            - redis
        services:
            celery:
                build: .
                scale: 1
                command: 'python celery'
    rabbitmq:
        size: large
        instances: 1
        loadbalance:
            - "9090:9090"
        services:
            rabbitmq:
                image: dockerfiles/rabbitmq
                loadbalance:
                    - "9090:9090"
    db:
        size: extra-large
        instances: 1
        loadbalance:
            - "5444:5444"
        services:
            pgbouncer:
                image:dockerfiles/pgbouncer
                links:
                    - db
                loadbalance:
                    - "5444:5444"
            db:
                image: dockerfiles/postgresql
    redis:
        size: large
        instances: 1
        loadbalance:
            - "1234:1234"
        services:
            redis:
                image: dockerfiles/redis
                loadbalance:
                    - "1234:1234"
```
## High level layout

```
+-------------------------+          +-----------------------+                                        
|                         |          |                       |                                        
|                         |          |                       |                                        
|       skipper.yml       |          |     .skippercfg       |                                        
|                         |          |                       |                                        
|                         |          |                       |                                        
|                         |          |                       |                                        
+-------------------+-----+          +----+------------------+                                        
                    |                     |                                                           
                  +-v---------------------v--+                                                        
                  |                          |                                                        
         +--------+           CLI            |                                          +------------+
         |        |                          |              +-------------------++      |            |
         |        +--------------------------+              |                   +------->            |
         |                                           +--+--->   Services         <------+ Builder    |
+--------v----------+               +----------------+--+   +------+-------------+      |            |
|                   |               |                   |                               +------------+
|                   +-------------> |                   |   +--------------------+                    
|   HOST (e.g. AWS) |               |       GROUP       +--->                    |                    
|                   |               |                   |   |  Instances         |                    
|                   |               |                   |   +--------------------+                    
+-------------------+               +----------------+--+                                             
                                                     |      +--------------------+                    
                                                     |      |                    |                    
                                                     +------>  Loadbalancer      |                    
                                                            +--------------------+                    
```
## Components
- [ ] a host-agnostic core module which defines groups and services, and talks to the other parts of the application #14 
- [ ] a command line interface which takes the configuration files and passes them to the core #15
- [ ] a registry module which builds services, stores them and retrieves them from a specified registry #16
- [ ] a series of host modules which implement host-wide methods, as well as an instance model with a consistent API used by the core. Suggested implementations:
  - [ ] AWS #17
  - [ ] Digital Ocean
  - [ ] Local 
  - [ ] Rackspace
  - [ ] Heroku
